name: meetups

services:
  django:
    container_name: meetups_django
    entrypoint: /app/entrypoint.sh
    build: .
    volumes:
      - .:/app  # Needed for cron-jobs file
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgres
      - rabbitmq
      - celery
    networks:
      - app_network
    restart: unless-stopped

  celery:
    container_name: meetups_celery
    build: .
    command: celery -A matcher.tasks worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - app_network
    restart: unless-stopped

  postgres:
    container_name: meetups_postgres
    image: postgres:15
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_network
    restart: unless-stopped

  rabbitmq:
    container_name: meetups_rabbitmq
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"  # RabbitMQ management console
      - "5672:5672"    # RabbitMQ default port
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    driver: bridge