#!/bin/sh
# Docker script to set up and run the Django app

# Generate /app/cron-jobs from environment variables (if all are provided)
generate_cron_from_env() {
    # Only overwrite when ALL three env vars are set (non-empty)
    if [ -n "${CRON_CREATE_ROUND:-}" ] && [ -n "${CRON_DO_ROUND:-}" ] && [ -n "${CRON_CHANNEL_ID:-}" ]; then
        mkdir -p /logs
        {
            echo "# generated by entrypoint on $(date -u)"
            echo "${CRON_CREATE_ROUND} /usr/local/bin/python /app/manage.py create_round ${CRON_CHANNEL_ID} >> /var/log/cron.log 2>&1"
            echo "${CRON_DO_ROUND} /usr/local/bin/python /app/manage.py do_round_matching ${CRON_CHANNEL_ID} >> /var/log/cron.log 2>&1"
            echo ""
        } > /app/cron-jobs
    else
        echo "cron-jobs file not created." >&2
    fi
}

start_supercronic_if_configured() {
    if [ -f /app/cron-jobs ]; then
        supercronic /app/cron-jobs
    fi
}

# Run Django management commands
python manage.py collectstatic --noinput
python manage.py makemigrations matcher
python manage.py migrate
python manage.py createsuperuser --no-input

# Create the cron-jobs file from environment variables if they are set
generate_cron_from_env

# Start supercronic and put it in the background
start_supercronic_if_configured &

# Start Gunicorn server
exec gunicorn meetups.wsgi:application --bind 0.0.0.0:$PORT
