name: Run Tests

on:
  push:
    branches: [ master, production ]
  pull_request:
    branches: [ master, production ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.4'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create test environment file
      run: mv .env.example .env
    
    - name: Run tests
      run: |
        DJANGO_SETTINGS_MODULE=meetups.settings.test python manage.py test
